### ISSUE TITLE
Build Core of Data Source Identification Pipeline

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-source-identification#10]
We want to automate the process of identifying URLs that have useful data sources and gathering all the necessary info on them to add them to our data sources table. We have some pieces built, this ticket is scoped to connect those and add some other initial basics.

- Given a list of potentially useful URLs, query the Supabase API data sources endpoint to eliminate any we already have. Here is a list of URLs for testing: https://github.com/Police-Data-Accessibility-Project/planning/files/9923552/cd3d48a5-b59c-4de0-a840-3301fb8c8618.csv
and an open ticket where identification is needed: https://github.com/Police-Data-Accessibility-Project/PDAP-Scrapers/issues/204
- Get HTML tags for the URLs using: https://github.com/Police-Data-Accessibility-Project/data-source-identification/tree/main/html-tag-collector
- Join to the output from this ticket on url to see if agency can be identified: https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/9
- Run the remaining URLs through this ML classifier to see which might be useful to us: https://github.com/Police-Data-Accessibility-Project/data-source-identification/tree/main/ml-url-classifier

**Comment by josh-chamberlain** [comment]
- I think `html-tag-collector` should be run just after we check for duplicates. The goal of using that is to give the rest of our pipeline more information, because URLs alone are frequently unhelpful. Can it be made part of the JSON package?
- Should we use our API for this instead of Supabase?

**Comment by mbodeantor** [comment]
Totally, I'll edit for both those

**Comment by josh-chamberlain** [comment]
We can also use this for testing: https://github.com/Police-Data-Accessibility-Project/scrapers/tree/main/utils/meta/open_data_network
