### ISSUE TITLE
Data Source Identifier: decide DB & API structure

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-source-identification#112]
## Context
- Part of #109 and #108 

We need a database + API to support the brain of our data source ID system.

### General goals:

- don't let the human labeling pile get too big / unmanageable
- be responsive to active `requests`
- don't spend time searching for stuff no one seems to be looking for
- aim for a thorough search of a geographic area before moving on to the next
  - in some cases, a thorough national or statewide search of a particular record type may be warranted
- An endpoint which accepts a batch of URLs, each with the metadata: `agency` (required) `record_type` (optional) `record_type_category` (optional) `relevance` (optional, yes or no)
  - other metadata from the data sources schema can be accepted
- The app should create a log of the batch, with the strategy used to generate it and basic facts about it
  - builds on the concept of batches: https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/96

### "Passive maintenance" collectors

These aren't triggered by a topical request or goal; they just happen slowly over time for overall database health and presence.

- crawling agency websites + looking for sources "nearby" other sources
- crawling lists of data sources and portals like MuckRock
- finding relevant stuff in common crawler

### "Active growth" collectors

These are triggered by our user's needs.

- auto-googler

### Current understanding:
- `batches` table ([prototyped here](https://github.com/Police-Data-Accessibility-Project/data-source-identification/blob/main/annotation_pipeline/data/batch_info.csv))
  - `strategy_used` to generate
    - may include keywords used, or other strategy-specific arguments
  - `count` of URLs in the batch
  - `date_generated`
  - `strategy_success_rate`, how often the URLs ended up approved in the database
    - in theory, even if they had to be human-labeled, it's a success of the staregy
  - `metadata_success_rate`, how much of the metadata we were able to ID with our models
    -  may want to separate into `agency_match_rate`, `record_type_match_rate`, and `record_category_match_rate`
  - `compute_time`, how long it took to generate the batch (good for understanding ROI)
- `urls` table
  - references the `batch` of each URL
  - has a subset of data sources metadata
  - `outcome` of each URL
    - `submitted`, `human_labeling`, `rejected`, `duplicate` (?)
- `missing` table
  - references a `place` or `agency` and the `record_type` we searched for and did not find, at what time, with what strategy
  - this could just be the `batches` table, depending on how it's structured

### API Endpoint
- `/batches` 
  - POST 
    -  An endpoint which accepts a batch of URLs, each with the metadata: `agency` (required) `record_type` (optional) `record_type_category` (optional) `relevance` (optional, yes or no)
    - Will create a batch with the requisite information, as well as indicate what, if any, of the urls given in the batch were rejected (for example: because they are duplicates of existing urls).
  - PUT batch
    - Updates metadata of an existing batch, such as success rate
  - GET batch
    - Gets an existing batch. No plans at the moment for multiple batches.
- `/urls`
  - PUT url
    - Modify attributes of a url, such as metadata, outcome, possibly other properties given in current `data-sources` design
  - GET url
    - Get metadata for a specific url
- `/source-collection` 
  - Each individual collector can have its own namespace, so `/source-collection/auto-googler`, `/source-collection/common-crawler` , etc.
  - `GET` to the `/source-collection` root can give a lot of all recent attempts (or up to some limit)
  - `POST` requests can provide the specific parameters which can then trigger the collector to activate
    - We can reserve a batch ID for this, so that we can have it exist as an identifier, even if it fails.
    - Once the collector finishes its session, it sends the batch to the namespace
  - `GET` requests can get the status of the source collector or a log of recent attempts — is it in progress? Did a batch fail?
    - Providing this information may in turn require a further `/status` subtype for each of these that the collector `POST`s to (i.e. `/source-collection/auto-googler/status`)

## Requirements

- [x] decide where the batch and url tables should be and their schema
   - currently batch = our own db and url = huggingface datasets; do we need to adjust this?
- [x] decide where the API endpoints should be and their schema
- [x]  come up with a plan for codifying our priorities and triggering automation of our collection tools
- [x] keep track of the money spent on compute time, and try to come up with a dollar amount for "sponsoring a county"
- [x] create automation for batch creation

**Comment by maxachis** [comment]
@josh-chamberlain Questions, in checklist format!

> PUT batch
> - Updates an existing batch 

- [ ] What parts of the batch do we envision updating? Individual entries? The metadata? Something else?

> GET batch
> - Gets an existing batch

- [ ] When we say an existing batch, do we mean all the entries within that batch?
- [ ] Do we want an option for getting the metadata of multiple batches?

> PUT url
> - Modify attributes of a url 

- [ ] What attributes do we envision being modifiable?

> GET url
> - Get specific url 

- [ ] Would this work by inputting the given URL? So provide the URL, get relevant metadata?

**Comment by maxachis** [comment]
# DB Diagram

I used the tools at DB Diagram to create a diagram of the database as we're envisioning it. A link to the diagram in question can be found [here](https://dbdiagram.io/d/Data-Source-Identifier-DB-6763598784c741072722f083).

Below is the image, and below _that_, the code that generated it (which helpfully doubles as a descriptor)
![image](https://github.com/user-attachments/assets/fedb073a-4010-4610-90d3-610b25d26aa9)


```
Table strategies {
  // Stores all higher-level strategies that can be used to generate a batch
  id integer [primary key]
  source varchar [note: 'The source of the strategy, e.g., CommonCrawler, MuckRock, etc.']
  description text [note: 'Description of the strategy']
}

Table strategy_parameters {
  /*
  Strategies often have multiple custom parameters.
  This table accounts for those
  */
  id integer [primary key]
  strategy_id integer [note: 'References the strategies table']
  parameter_key varchar [note: 'Name of the parameter']
  parameter_value varchar [note: 'Value of the parameter']
}

Table batches {
  // Stores information on all batches
  id integer [primary key]
  strategy_id integer [note: 'References the strategies table']
  count integer [note: 'Number of URLs in the batch']
  date_generated timestamp
  strategy_success_rate float [note: 'How often URLs ended up approved in the database']
  metadata_success_rate float [note: 'Percentage of metadata identified by models']
  agency_match_rate float [note: 'Rate of matching to agencies']
  record_type_match_rate float [note: 'Rate of matching to record types']
  record_category_match_rate float [note: 'Rate of matching to record categories']
  compute_time interval [note: 'Time taken to generate the batch']
}

Table urls {
  // Stores all URLs included in all batches
  // TODO: Suppose one batch is submitted which contains a url already present in another batch: What do we do?
  id integer [primary key]
  batch_id integer [note: 'References the batch this URL belongs to']
  metadata jsonb [note: 'Subset of data sources metadata']
  outcome varchar [note: 'Outcome of the URL: submitted, human_labeling, rejected, duplicate, etc.']
  created_at timestamp
}

Table missing {
  // Unclear if we need this separately; may be consolidated into `batch`
  id integer [primary key]
  place_id integer [note: 'References a place or agency']
  record_type varchar [note: 'Type of record searched for but not found']
  batch_id integer [note: 'References the batch if applicable']
  strategy_used text [note: 'Strategy attempted for the search']
  date_searched timestamp
}

Ref: urls.batch_id > batches.id // many-to-one

Ref: missing.batch_id > batches.id // many-to-one

Ref: batches.strategy_id > strategies.id // many-to-one

Ref: strategy_parameters.strategy_id > strategies.id // many-to-one
```

**Comment by josh-chamberlain** [comment]
@maxachis I answered your questions inline; I figure you can check them off if the answers are satisfactory. I would not presume!

**Comment by josh-chamberlain** [comment]
@maxachis I'm a little confused about the `strategies` situation—would there be a `strategies` entry for every batch? or, a `strategy_parameters` entry for every batch?

Originally, I was thinking we could just dump a JSON blob into `batches.strategy` for each row:

```
{
   "strategy_name": "Auto-Googler",
   "parameters": {
      "key1": "value",
      "key2": "value"
   }
}
```

or separate `strategy` and `parameters` columns. We could always parse it later, but I don't think we have _much_ call for accessing these programmatically.

It's human-readable right in the table, without any lookups. I'm open to hearing the advantages of the more formal table structure, too!

**Comment by maxachis** [comment]
> @maxachis I'm a little confused about the `strategies` situation—would there be a `strategies` entry for every batch? or, a `strategy_parameters` entry for every batch?
> 
> Originally, I was thinking we could just dump a JSON blob into `batches.strategy` for each row:
> 
> ```
> {
>    "strategy_name": "Auto-Googler",
>    "parameters": {
>       "key1": "value",
>       "key2": "value"
>    }
> }
> ```
> 
> or separate `strategy` and `parameters` columns. We could always parse it later, but I don't think we have _much_ call for accessing these programmatically.
> 
> It's human-readable right in the table, without any lookups. I'm open to hearing the advantages of the more formal table structure, too!

The way I envisioned this (note the past tense), was:
1. We'd have a formal strategies table describing each of our specific unique means of obtaining batches. So Auto-Googler gets one strategy entry, 
2. By contrast, each batch would come with its own set of parameters, listed in a key value pair (like JSON)

Buuuut if we can just do JSON as a parameter in the batch, we don't necessarily need 2. And maybe we can just have a database enum for each type of strategy.  Unless we envision some requisite metadata for each strategy, having a separate table is probably superfluous. And if we _do_ decide we need that, it's simple enough to create.

So with that, I've updated and simplified the table design.

**Comment by maxachis** [comment]
@josh-chamberlain I've got ideas for additional endpoints:

## `/source-collection` namespace
- Each individual collector can have its own namespace, so `/source-collection/auto-googler`, `/source-collection/common-crawler` , etc.
- `GET` to the `/source-collection` root can give a lot of all recent attempts (or up to some limit)
- `POST` requests can provide the specific parameters which can then trigger the collector to activate
  - Once the collector finishes its session, it sends the batch to the namespace
- `GET` requests can get the status of the source collector or a log of recent attempts — is it in progress? Did a batch fail?
  - Providing this information may in turn require a further `/status` subtype for each of these that the collector `POST`s to (i.e. `/source-collection/auto-googler/status`)

**Comment by josh-chamberlain** [comment]
@maxachis nice, this is a great idea! I like the structure. Sound.

**Comment by maxachis** [comment]
So here's my latest creation: SourceBrain! 

```mermaid
flowchart TD

CM{Collector Manager}
SB((fa:fa-brain SourceBrain))
style SB fill:#30b369, color:#000000
style API fill:#700c1d
style DB fill:#5b73c9
style CM fill:#ba680b, color:#000000
DB[(Database)]

SB <--> DB
SB <--> CM
API --> SB
subgraph collectors
CM <--> CKAN(CKAN)
CM <--> CC(CommonCrawler)
CM <--> MR(MuckRock)
CM <--> E(AutoGoogler)
end
API[\API/]
```

SourceBrain, in my devising, will internally orchestrate the various collectors (via the Collector Manager subcomponent), interface with the database, and interact with other systems via its API. The way it works is:
1. The API will receive requests and send them to SourceBrain Main
2. SourceBrain Main will use the database to evaluate those requests. If the request is to start a batch, it will send a command to the Source Collector.
3. The Source Collector orchestrates a collection of urls, gathers them into a standardized batch format[^1], and send that back to SourceBrain Main, where it will be routed to the database. 
- [ ] We could add some degree of asynchronicity to this, so people could query SB or queue up multiple batches to run while it still operates its internal processing, but that requires thought.
[^1]: We will need to decide on what the standardized batch format is

```mermaid
---
title: How SourceBrain Sends Sources
---
flowchart LR

DB[(Database)]
PDAP(PDAP Client)
SB((fa:fa-brain SourceBrain))
style SB fill:#30b369, color:#000000
style API fill:#a40dd6, color:#000
style DB fill:#5b73c9
style PDAP fill:#b0250c, color:#000

subgraph SourceBrain System
DB <--> SB
SB <--> PDAP
end
PDAP <--> API
API[\Data Sources API/]
```

SourceBrain will use its own PDAP Client to translate internal commands to external requests to the Data Sources API. It'll take urls in its own database and submit them via API requests to the Data Sources database.
- [ ] It may also be able to use this to synchronize its own database with that of the Data Sources API, but unclear.
- [ ] These could occur automatically once a batch is started, or we could wait for explicit command via the SourceBrain API before we send it to DS (where it will have to be reviewed anyway, but still)

**Comment by josh-chamberlain** [comment]
@maxachis you seem quite fluent with mermaid but I'll note that if you extend this line by adding a hyphen:

```
PDAP --Requests data, submits sources/agencies--> DSAPI
↓
PDAP --Requests data, submits sources/agencies---> DSAPI
```

You can make the charts sit atop one another.

Anyway, more importantly: 

- I think the primary goal of `Collector Manager` should be to make writing and maintaining a Collector as easy as possible; these modules are going to change, break, and go out of date frequently. The collector manager should be well-documented and make its needs and function clear. It should be obvious what a collector's inputs and outputs must be, with the rest being glorious trial and error. These are things which may have occurred to you, but I think having one clear main goal for a module is best!
- Setting up the API but not automating it makes sense to me. We have automation manager for that!
- For managing the queue, I found [wakaq](https://github.com/wakatime/wakaq)? Also, here's a thing I found about [token bucket vs leaky bucket](https://www.eraser.io/decision-node/api-rate-limiting-strategies-token-bucket-vs-leaky-bucket).
