### ISSUE TITLE
Data Source Identification: Batch Creator

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-source-identification#116]
## Context

Part of #108

This is about codifying and orchestrating our strategies for data source collection. We have the #109 , so we can create batches with a variety of strategies—how should we decide when to create batches?

### Goals

- don't let the human labeling pile get too big / unmanageable
- be responsive to active `requests`
- don't spend time searching for stuff no one seems to be looking for
- aim for a thorough search of a geographic area before moving on to the next
  - in some cases, a thorough national or statewide search of a particular record type may be warranted

### "Passive maintenance" collectors

These aren't triggered by a topical request or goal; they just happen slowly over time for overall database health and presence.

- crawling agency websites + looking for sources "nearby" other sources
- crawling lists of data sources and portals like MuckRock
- finding relevant stuff in common crawler

### "Active growth" collectors

These are triggered by our user's needs.

- auto-googler

## Requirements

- [ ] come up with a plan for codifying our priorities and triggering automation of our collection tools
- [ ] keep track of the money spent on compute time, and try to come up with a dollar amount for "sponsoring a county"
- [ ] create automation for batch creation

**Comment by maxachis** [comment]
Move this documentation into #112!
