### ISSUE TITLE
Manual Data Source Identification

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-source-identification#13]
Start going through URLs that have made it through the other steps in the identification process to and manually add a name, description, and other metadata with an eye to how best organize and simplify this process to make it as streamlined as possible. As you notice any patterns emerging, experiment with automation around those.

**Comment by josh-chamberlain** [comment]
@mbodeantor

1. Using these as a starting point might be good:
   - https://airtable.com/shrUAtA8qYasEaepI has names and descriptions, for the most part
   - [doccano-record-types-230828.csv](https://github.com/Police-Data-Accessibility-Project/data-source-identification/files/12456522/doccano-record-types-230828.csv)
   `doccano` is the pipeline we can use to manually label datasets. I can give you access to that if you want to learn more or use it, but this is all we have labeled.

2. In Airtable, `name` defaults to "`record type` for `agency name`" which I think should be used here as a baseline.

3. We have ChatGPT pro, which I think allows us to use their API. We could try feeding it content from `html_tag_collector` to see what kinds of names and descriptions it gives us. We could experiment with giving it prompts and examples, or even training our own model (I have no idea if we have enough data for training). We have `ml-url-classifier` as a starting point.

**Comment by josh-chamberlain** [comment]
closing as too broad to be currently relevant
