### ISSUE TITLE
update dataset & model to include HTML tags

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-source-identification#28]
builds on https://github.com/Police-Data-Accessibility-Project/data-source-identification/pull/27

we have a dataset: https://huggingface.co/datasets/PDAP/urls

- [x] include data from the HTML tag collector in the huggingface URLs dataset
- [x] train the model and see if it's improved

**Comment by mbodeantor** [comment]
This will consist of adding the ml-url-classifier to the identification_pipeline and then including the tags as features in the model

**Comment by josh-chamberlain** [comment]
@bonjarlow you mentioned this working—maybe not perfectly, but working—a few updates back. If you point to the code where that's accomplished in HF or GitHub, we can close this 👀
