### ISSUE TITLE
Restructure Repository For Improved Organization

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-source-identification#35]
A few recommendations for restructuring the repository to improve organization:

### Requirements Files

- There are currently several requirements files specific to directories as well as a global requirements file. We should have one or the other. Since these are all part of the same pipeline and they're meant to be run together, that probably means consolidating everything into a single global requirements file. 

### Virtual Environment Directory in openai-env

- Because virtual environments are specific to a user's setup and can contain absolute paths specific to a user's machine, recommend replacing this with `requirements.txt` or `environment.yml`. 

### 'tests' and 'modules' directories

- Create `tests` directory for running unit tests
- To avoid cluttering up the repo and then ensuring logical organization, make all currently existing non-'tests' directories be subdirectories of new `modules` directory

**Comment by mbodeantor** [comment]
Using requirements.txt would align with other repos

**Comment by maxachis** [comment]
@mbodeantor @josh-chamberlain I'm also wondering whether the repository should be broken up into two (or more?) repositories. At the moment, the repository includes folders handling initial data gathering and pre-processing (`common_crawler`, `html_tag_collector`, and `agency_identifier`), machine learning components (`hf_testing`, `hugging_face`, and `ml-url-classifier`) and per Issue #19 eventually include a directory that would involve interfacing with Label Studio. 

This may pose an issue for several reasons:

1. The repository now includes a variety of vastly different packages which would need installing -- bulky machine learning packages on one end and comparatively svelte ones for interfacing with databases or APIs. 
2. The overall organization is already somewhat cumbersome -- having to step around so many folders irrelevant to a particular task adds friction to development
3. The Github repository contains substantially different issues, which adds more visual clutter for people focusing on only one domain and may intimidate potential new developers. 
4. CI/CD such as through Github Actions may be affected, as cloning the entire repository (much less installing all packages) is unlikely to be necessary for any individual action. And since some of the automations are likely to be asynchronous with others (i.e. machine learning with initial URL retrieval), that reduces the need to keep them in the same place.
5. Team organization and permissions might be more difficult. If we want to get more granular in terms of who gets access to what component (for example, maybe we only want certain people to focus on or have access to the machine learning portion), breaking up would be recommended.

Let me know your thoughts.

**Comment by josh-chamberlain** [comment]
@maxachis re: splitting into multiple repos

1. valid—though, isn't this also an argument for keeping a requirements file in each individual module?
2. valid, though seems low-impact
3. valid, these are probably due for a cleanout too. managing that complexity by moving things to the roadmap is supposed to make things easier for folks just starting out.
4. valid, though keeping things as modules in subfolders seems like it should be OK
5. not worried about this—we're pretty open

I think most of these points are solved if we treat each directory in the main repo as its own little repository with a README and such. A big downside of splitting into multiple repos: what if I need to make changes that affect multiple modules? Multiple PRs that need to be approved/deployed in sync? That's why data-sources-app is a monorepo, even though the client and back end are two apps. DigitalOcean makes it pretty easy to deploy from a directory in a repo.

In this case, maybe we could do two repos: "managing labeling tasks to train ML models" and "identifying URLs using ML models".

**Comment by maxachis** [comment]
@josh-chamberlain I think these points all make sense. 

Going back to the requirements issue, I realize I made a PR which consolidated them, but the more I think about it -- and especially if we're going to stay the course of having a repo with multiple modules -- I'm not sure what the proper course of action is. 

My current attempt at compromise in my more recent PRs (which also involve constructing Github Actions) has been to have a globally populated requirements.txt file but also have a requirements file in the module directory which specifies what requirements are needed for the associated Github action, which obviously undercuts my initial attempt to consolidate the requirements files. 

It may be, in contradiction to my prior assertion, that having a global requirements folder for shared imports (such as pytest) and module-specific requirements folders is the proper way to go.

**Comment by josh-chamberlain** [comment]
@maxachis yeah, it's hard to know in advance what will be best. Even shared requirements can break if two modules demand different versions.

Self-contradiction is a sign of a thoughtful person. Right?

**Comment by maxachis** [comment]
> Self-contradiction is a sign of a thoughtful person. Right?

Well if not, I have bad news for you about the person you've hired. 

Anyway, all this to say that I've concluded what you already know, that premature optimization vis-a-vis requirements probably doesn't make sense here. I do think that further down the line, it'll be worth doing once we're more settled on a system.

**Comment by josh-chamberlain** [comment]
@maxachis how do you feel about this issue?

**Comment by josh-chamberlain** [comment]
we decided to close for now, though revisiting is an option
