### ISSUE TITLE
HTML scraper: grab alternate text if headers/meta are not available

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-source-identification#55]
### Context

(reported by @bonjarlow) Many of our training sources don't have h1–6 or meta tags; not every page follows those conventions. 

example: https://www.longbeach.gov/police/press-releases/traffic-fatality---palo-verde-ave-and-los-coyotes-diagonal/

### Ideas for execution

This one is flexible. The goal is to keep the data package + rules/code to generate it simple.

- idea: if we don't have headers, we could experiment with other forms of emphasized text. The idea is just to give the model some idea of relevance/weighting for the bits of text.
- idea: pull content from tags and elements in order until we hit a character limit
- idea: condense the columns so that we have one property each for "emphasized" (headers, `<b>`, `<strong>`, etc) , "text", and "meta". I'm open to discussion about what exactly those categories should be, but I don't think the ML models care too much and it's a lot of columns.
- change the name of this tool to `source-text-collector` or `html-text-collector` if the functionality changes and it's not too inconvenient

**Comment by maxachis** [comment]
I would add onto this that we may additionally want to consider if we get _too much_ content from certain web pages and want to pare it down. 

A simple way to do this might be by having a hierarchy of tags and gradually taking more from lower tags until we reach a certain amount.

Another amount might involve keyword extraction, where we might use NLP to pull only the most important content from a web page. 

We could additionally try out several methods and compare them.

**Comment by maxachis** [comment]
Another element to consider is the presence of [stop words](https://en.wikipedia.org/wiki/Stop_word), which is to say words with little to no meaningful content, such as "a", "the", "of", and so on. This might be a bit more delicate, as what might constitute a stop word can vary with context (e.g., "to be or not to be" contains nothing but common stop words but obviously carries a lot of significance), but is worth considering especially if the ML tools we're utilizing don't necessarily take into account the ordering and sequencing of words as much.

**Comment by maxachis** [comment]
### Notable test cases

1. https://www.longbeach.gov/police/press-releases/traffic-fatality---palo-verde-ave-and-los-coyotes-diagonal/ - No h1-h6 tags. No meta tag in header. 

Will add more as I discover them.

**Comment by maxachis** [comment]
I've created a PR (#58) that adds keyword extraction logic to `collector.py`. 

This addresses requirement 4 and partially addresses requirement 2. For requirement 2, this utilizes the [KeyBERT](https://maartengr.github.io/KeyBERT/api/keybert.html#keybert._model.KeyBERT) model to extract what it identifies as keywords most relevant to the document. 

The rationale is as follows:

1. This method is designed to be agnostic towards what tags are included-- it looks at the raw text of the web page, without dividing it into tags. This obviates the need for at least some tag-specific logic.
2. It is also robust to the size of the web page. Regardless of whether the web page is very large or very small, it is designed to find 10 keywords. 

Caveats:
1. This hasn't been tested on all possible web pages, so it is unclear where it might struggle.
2. BERT and keyword extraction is typically designed for linear content, and web pages are not always linear. This could add unexpected behavior.

**Comment by maxachis** [comment]
> [ ] 1. We should grab the first `some number` of characters—5000? 862?—and put those in the data package.

@josh-chamberlain Not sure how useful this would be. The first _n_ characters might be the navbar, for example, or other information not directly relevant to the web page. Additionally, the importance of those first _n_ characters would vary depending on the overall size of the web page -- for a small web page, it'd probably be quite useful. For larger web pages, not so much.

**Comment by josh-chamberlain** [comment]
@maxachis OK, I updated my comment. I would see #58 as a valid enhancement, especially as a fallback for cases where we don't have good content, but I'm slightly worried about playing telephone and losing fidelity through successive BERT interpretations.

**Comment by bonjarlow** [comment]
@josh-chamberlain @maxachis hi y'all, adding some thoughts here:

I've tested a method to grab the first 500 words from any `<div>` text (which I think includes any `<p>, <span> or <a>` tags as mentioned by Max?) in the tag collector and it's working! It's filling in empty token space which is great, and on a first test validity has gone up to 83%. 

This definitely can be refined, it grabs junk at times ("Follow us on instagram" etc.). this occurs in the headers as well, but for samples like:

> https://www.longbeach.gov/police/press-releases/traffic-fatality---palo-verde-ave-and-los-coyotes-diagonal/ - No h1-h6 tags. No meta tag in header.

it's working as we'd hoped.

> idea: if we don't have headers, we could experiment with other forms of emphasized text. The idea is just to give the model some idea of relevance/weighting for the bits of text.

Right now there isn't a good sense of weighting in the input text / tokens, it just jams all of the feature columns together into a blob and tokenizes. There is a way to give an attention mask to the tokens, but afaik it's binary and doesn't allow for any hierarchy. I'll look more into this however cause it could be really helpful.

> A simple way to do this might be by having a hierarchy of tags and gradually taking more from lower tags until we reach a certain amount.

This is essentially being done already in the tokenizer. The tokens fill up in order of url, html_title, meta_desc, h1, h2, ... down the line to div text. If it hits 512 then anything down the line is truncated.

lastly, a lot of the urls with no meta description or headers are pdfs, so possibly we look into a pdf scraper on top of the html scraper.

**Comment by josh-chamberlain** [comment]
@bonjarlow @maxachis so what do y'all think about using the `grab 500 words` method as a fallback, only if the `<h>` tags are blank?

**Comment by bonjarlow** [comment]
so it looks like the model is ~5% better when keeping div text always, so that would be my recommendation. Is maintaining neatness in the dataset your main concern @josh-chamberlain ? There are a lot of columns, so I definitely wouldn't mind merging h1-6, and as you mentioned it would have no impact on the model or weighting of terms at this point

**Comment by josh-chamberlain** [comment]
@bonjarlow yeah, I'm just looking to reduce complexity, but it's not an absolute requirement.

**Comment by maxachis** [comment]
@josh-chamberlain @bonjarlow If Jon says it improves quality of data by 5% than I say include it. I will offer a few points of possible caution:

1. It may be useful at some point to see if there is particular content which is effectively constant amongst our data -- if certain content provides no useful means to differentiate one row from another, it's likely not useful to us. 
2. While we don't appear to be at the point where excess data risks a negative impact, we should be mindful of that when considering additional data sources. At a certain point, additional data will likely lead to diminishing returns and could even reduce quality in terms of noise or bias.

@bonjarlow With Josh's blessing, would you be able to create a PR that could add the div data extraction method to the pipeline?
