### ISSUE TITLE
test annotation workflow (1 batch)

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/data-source-identification#68]
### Context

Closed #19. We have a basic annotation workflow in Label Studio, currently called "Text annotation of URLs".

<img width="658" alt="Screen Shot 2024-04-03 at 8 33 59 PM" src="https://github.com/Police-Data-Accessibility-Project/data-source-identification/assets/30379833/b3887bdd-423c-4f61-a1ca-672af5c3be75">

### Requirements

Generally, follow [the diagram here](https://github.com/Police-Data-Accessibility-Project/data-source-identification?tab=readme-ov-file#training-models-by-batching-and-annotating-urls). 

While manually running through this process, identify blind spots or places where the diagram is unclear/insufficient.

1. Generate a batch using common_crawler, and log it (even manually in this repo is fine for now)
   - may want to wait for #66, you can test the fix for that issue here: https://github.com/Police-Data-Accessibility-Project/data-source-identification/pull/70 
3. Use the source_tag_collector on the batch
4. Add it to Hugging Face
5. optional: pre-check it with our relevance model?
6. Send it to Label Studio as labeling tasks
7. Do some labeling (I can help with this part, I want to document it)
9. Update training data

**Comment by bonjarlow** [comment]
@josh-chamberlain @maxachis @EvilDrPurple 

I've run through the annotation workflow, here are some observations

### Common Crawl

- either during or after common crawl take care of duplicate urls (sometimes contains both https://www... and https://... for same page)

### Label Studio

To interact w the api need {project id} and authorization token:

- import tasks:

`curl -H 'Authorization: Token abc123' -X POST 'https://app.heartex.com/api/projects/{project id}/import' -F ‘file=path/to/my_file.csv’`

- export annotations:

`curl -X GET 'https://app.heartex.com/api/projects/{project id}/export?exportType=CSV' -H 'Authorization: Token abc123' --output 'path/to/output.csv'`

- make sure to change label from 'record-type' to 'record_type' in the published interface to match HF database
- if multiple exports happen in the same labelstudio project they each will contain all previous annotations as well, so need to make sure we either remove annotations that have already been exported, or keep track of ids of exported annotations and only append new ones to database

### HuggingFace

- need to reorder/drop columns in labelstudio export file to match huggingface database
- type check columns as well (will not concatenate int64s to a float64 column e.g.)
- map record_type to new coarse_record_type column
- append new annotations to original dataset and then push_to_hub, or upload batches of csv's? both work (eg. https://huggingface.co/datasets/PDAP/training-urls vs. https://huggingface.co/datasets/PDAP/unlabeled-urls)
    - appending to original dataset seems safer, it won't update if columns/types don't match. not sure what happens if mismatched data is present in batched files. do have to interact through a hugginface 'dataset' object
    - though if we needed to remove samples for any reason may be easier if things were done in batches

### ps

- id scheme? a way to match id to a common-crawl batch that'd be nice
- common crawl batches targeted at specific coarse record types to keep even label distribution
- last updated property? one for the whole dataset or per sample?
- make a new dataset on hugging face for urls post tag-collector, pre annotation?

**Comment by josh-chamberlain** [comment]
@bonjarlow thank you for the test + report back!  how do you propose we harden these steps you took into a repeatable process? I could see a doc for this process, maybe in here: https://docs.pdap.io/meta/operations/staff and linking it in the README. Or, we could make a simple script / CLI workflow which guides us through doing this. It'll be relatively infrequent, and always done by a high-context staff person. Your thoughts?




> either during or after common crawl take care of duplicate urls (sometimes contains both https://www/... and https://... for same page)

seems like a worthy enhancement: https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/83

> append new annotations to original dataset and then push_to_hub, or upload batches of csv's? both work (eg. https://huggingface.co/datasets/PDAP/training-urls vs. https://huggingface.co/datasets/PDAP/unlabeled-urls)
>   - appending to original dataset seems safer, it won't update if columns/types don't match. not sure what happens if mismatched data is present in batched files. do have to interact through a hugginface 'dataset' object
>   - though if we needed to remove samples for any reason may be easier if things were done in batches

Keeping each batch in its own file seems to make sense to me, but that's in concept and not technical. Adding a batch id to the training dataset so we can trace its origin would also be OK. the goal is just to log and identify problems.

> id scheme? a way to match id to a common-crawl batch that'd be nice

yep, we should match the common crawl batch ID

> common crawl batches targeted at specific coarse record types to keep even label distribution

yes, good idea. we could even tell people this when they're labeling—and make simpler labeling interfaces for "are these arrest records or not"

> last updated property? one for the whole dataset or per sample?

What are you trying to track here? I'm just not sure what you mean.

> make a new dataset on hugging face for urls post tag-collector, pre annotation?

I think that once we run tag-collector, the dataset is improved, and we're not losing any information—I think overwriting the original dataset, or just adding tags to it, would be OK, unless you have another reason for wanting to make a new one.

**Comment by josh-chamberlain** [comment]
closing this one as completed and #88 is in progress
