### ISSUE TITLE
Identify Agencies

### ISSUE THREAD

**Issue by mbodeantor** [Police-Data-Accessibility-Project/data-source-identification#9]
As part of the Data Source Identification Pipeline, we want attach to discovered data sources the agency they are associated with. To aid in this process, we should utilize the Sitemap Scraper tool that was developed: https://github.com/Police-Data-Accessibility-Project/PDAP-Scrapers/tree/c7ecd224c2aab66666a96832bea6bc11b69de623/utils/sitemap_scraper

- Query the data-sources-app API Agency endpoint for all agencies with a URL and their name
- Modify Sitemap Scraper so the output retains the root URL and agency name
- Run the agency URLs through the sitemap scraper

**Comment by josh-chamberlain** [comment]
The sitemap scraper will reveal some good stuff, but many data portals use a different base URL than the homepage. I'm not sure how we should solve for that, but I suspect there is lurking work to do on this. We should also look at identifying the agency using contextual information on the page.
